[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cmds = [
    "cd frontend && npm install",
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "echo \"APIFY_API_TOKEN=${APIFY_API_TOKEN}\" > .env",
    "echo \"EXA_API_KEY=${EXA_API_KEY}\" >> .env"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
